nextstrain/dengue

README.md
Historically, the dengue pipeline had been pulling from a Fauna (RethinkDB) database. However, the pipeline has since been updated to pull from data.nextstrain.org instead (commit https://github.com/nextstrain/dengue/commit/c755bdc887b65c3040d432d39c26e90c5afe3476). 
This pull request would update the README to reflect that change and also provide an opportunity to update any links, wording, and documentation for the dengue pathogen pipeline. 
Please feel free to suggest other changes, especially as such changes may help document a standard README across dengue, [zika](https://github.com/nextstrain/zika), [ebola](https://github.com/nextstrain/ebola), or any other currently existing Nextstrain/PATHOGEN repository.
=> docs: drop obsolete fauna instructions

ingest/Snakefile, ingest/bin/infer-dengue-serotype.py, ingest/config/config.yaml, ingest/workflow/snakemake_rules/split_serotypes.smk, ingest/workflow/snakemake_rules/transform.smk
Split records by serotype by using the virus-tax-id field in NCBI datasets. Historically, we obtained each serotype individually in [this code](https://github.com/nextstrain/dengue/blob/9dbccc42f083302567a7ae5db7adeab452a1fb87/ingest/workflow/snakemake_rules/fetch_sequences.smk#L18-L24), leading to redundant fetching and processing of each sequence. Now that we're using ncbi datasets, these numeric IDs are recorded in a `virus-tax-id` field, that we can use to separate the serotypes.
1. Pull `virus-tax-id` and `virus-name` from the dengue NCBI dataset
2. Use the `virus-tax-id` to infer the `ncbi_serotype` field of each record
3. Use the `ncbi_serotype` field to split sequences and metadata files into serotypes
4. Update target files in the Snakefile to reflect the new serotype split
* …
=> Split by serotype using NCBI virus_tax_id

phylogenetic/README.md, phylogenetic/build-configs/nextstrain-automation/config.yaml, phylogenetic/build-configs/nextstrain-automation/deploy.smk
Adds a custom config and rules for deploying the final Auspice dataset of the phylogenetic workflow.
From [slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1711499690732839?thread_ts=1711066498.238259&cid=C01LCTT7JNN), had permission to duplicate changes from https://github.com/nextstrain/zika/pull/51
* Tried to exactly duplicate: https://github.com/nextstrain/zika/pull/51
=> Add nextstrain-automation build-configs to phylogenetic worklfow

.github/workflows/ingest-to-phylogenetic.yaml, ingest/build-configs/nextstrain-automation/upload.smk, phylogenetic/Snakefile, phylogenetic/rules/export.smk
Coordinated with @joverlee521 to copy commits from zika PR: https://github.com/nextstrain/zika/pull/52
Adds a single GH Action workflow to automate the ingest and phylogenetic workflows, set to run daily at the same time as the [automated mpox ingest](https://github.com/nextstrain/mpox/blob/e439235ff1c1d66e7285b774e9536e2896d9cd2f/.github/workflows/fetch-and-ingest.yaml#L4-L21). 
Uses GH Action caches to store hash of ingest results' `Metadata.sha256sum` values [added to the S3 metadata within upload-to-s3](https://github.com/nextstrain/ingest/blob/c0b4c6bb5e6ccbba86374d2c09b42077768aac23/upload-to-s3#L44). If the cache contains a match from previous runs of the GH Action workflow, then the workflow will skip the phylogenetic job. 
See commits for details.
Based on discussion in …
=> Automate ingest and phylogenetic workflows

phylogenetic/config/auspice_config_all.json, phylogenetic/config/auspice_config_denv1.json, phylogenetic/config/auspice_config_denv2.json, phylogenetic/config/auspice_config_denv3.json, phylogenetic/config/auspice_config_denv4.json, phylogenetic/config/config_dengue.yaml, phylogenetic/example_data/metadata_all.tsv, phylogenetic/example_data/metadata_denv1.tsv, phylogenetic/example_data/metadata_denv2.tsv, phylogenetic/example_data/metadata_denv3.tsv, phylogenetic/example_data/metadata_denv4.tsv, phylogenetic/rules/prepare_sequences.smk
I missed this in review of https://github.com/nextstrain/dengue/pull/38.
The phylogenetic workflow was still pulling from old S3 URLs
and not the ingest workflow output data.
=> Fix phylo input

phylogenetic/rules/export.smk
~Explicitly state that the root-sequence.json file is an expected output of the core phylogenetic workflow.~
~This also ensures that the Nextstrain automation rule `deploy_all` will include the root-sequence.json in the upload.~
Based on feedback from @jameshadfield in
https://github.com/nextstrain/zika/pull/56#issuecomment-2058060422
Looking at the existing dataset files on S3,
the 5-6 KiB root-sequence.jsons are pretty negligible when the main
Auspice JSONs are 600-800 KiB. Nextstrain datasets are limited by the
500MB memory cap in Chrome,¹ so we'd be fine adding the
root sequence inline.
This ensures that our uploads will include the root sequence so that
they don't get out-of-sync with the main Auspice JSON.
¹ https://github.com/nextstrain/auspice/issues/1622
Follow up to …
=> phylogenetic: Use inline root sequence

ingest/bin/calculate-gene-converage-from-nextclade-translation.py, ingest/defaults/config.yaml, ingest/rules/nextclade.smk
Several approaches were explored to add `{gene}_coverage` columns during ingest workflow (as opposed to during phylogenetic workflow). The different approaches were summarized by @joverlee521 and @jameshadfield and copied here for context of this PR, along with added comments from @j23414 in **\[comments\]**: 
1. Generalize RSV's [extend-metadata](https://github.com/nextstrain/rsv/blob/8eaf4cf8bbc67f267569881790d908c5719ae1aa/ingest/bin/extend-metadata.py) to take gene coordinates as input to calculate gene coverage. This will require gene coordinates to be maintained in the config YAML. Follow current pattern of outputing gene coverage columns that can be used for filter **\[ Opened an issue: https://github.com/nextstrain/rsv/issues/57 ~ @j23414 \]**
2. Use Nextclade's failedCdses column …
=> Add gene coverage columns during ingest workflow

ingest/rules/nextclade.smk
After discussion, it became clear that keeping `gene_coverage` columns a numeric value may simplify the subsequent augur filter command.
* https://github.com/nextstrain/dengue/pull/18
=> Instead of '?', set default gene_coverage to 0

.github/workflows/ingest-to-phylogenetic.yaml, .github/workflows/ingest.yaml, .github/workflows/phylogenetic.yaml
Copies independent workflows from zika PR: https://github.com/nextstrain/zika/pull/55 with modifications for dengue.
Would allow for trial runs of branches, while working on different dengue PRs
https://github.com/nextstrain/zika/pull/55
=> Add independent ingest and phylogenetic GH Action workflows

phylogenetic/Snakefile, phylogenetic/config/color_orderings.tsv, phylogenetic/config/config_dengue.yaml, phylogenetic/rules/annotate_phylogeny.smk, phylogenetic/rules/export.smk, phylogenetic/rules/prepare_sequences.smk
Following up on the [Generating gene reference files PR](https://github.com/nextstrain/dengue/pull/47), use the E gene reference files to create E gene trees.
**Visual summary** ([view whole pipeline plan so far](https://github.com/nextstrain/dengue/issues/17#issuecomment-2099514417))
- Issue: [Add E gene builds #17](https://github.com/nextstrain/dengue/issues/17)
- Earlier PR: [Add E gene trees #18](https://github.com/nextstrain/dengue/pull/18)
- Related PR in Measles: [Make tree for 450bp of the N gene ("N450) in Measles PR#20](https://github.com/nextstrain/measles/pull/20) which included changes suggested by some [2024-03-12 Nextstrain Gene Tree slides](https://j23414.github.io/2024-03-12_Nextstrain_Gene_Trees.pdf).
Links to resulting trees below
|  | genome  | E gene |
| :-- | :-- | …
=> Use gene reference files to generate E gene trees

.github/workflows/phylogenetic.yaml, phylogenetic/config/config_dengue.yaml, phylogenetic/rules/prepare_sequences.smk
Fixes https://github.com/nextstrain/dengue/issues/49
* https://github.com/nextstrain/dengue/issues/49
* Nice to have to test a future PR for https://github.com/nextstrain/dengue/compare/main...consistent-serotype-genotype-column-names
* which is addressing Issue: https://github.com/nextstrain/dengue/issues/41
Serotype expanded as expected
```
rule download:
output: data/sequences_denv3.fasta.zst, data/metadata_denv3.tsv.zst
jobid: 86
reason: Missing output files: data/sequences_denv3.fasta.zst, data/metadata_denv3.tsv.zst
wildcards: serotype=denv3
resources: tmpdir=/tmp
curl -fsSL --compressed https://data.nextstrain.org/files/workflows/dengue/trials/serogeno20240518/sequences_denv3.fasta.zst --output data/sequences_denv3.fasta.zst
curl -fsSL --compressed …
```
=> Add configurable staged input files for the `phylogenetic` github action

phylogenetic/README.md
Fixes: https://github.com/nextstrain/dengue/issues/52
Updates the links of the FASTA and metadata in the phylogenetic README. This probably should have been part of a previous PR: https://github.com/nextstrain/dengue/pull/40
* https://github.com/nextstrain/dengue/issues/52
* https://github.com/nextstrain/dengue/issues/22
- No functional changes, this is mainly updating the documentation
=> Fixup: update the links of FASTA and metadata in the README

ingest/defaults/annotations.tsv, phylogenetic/config/exclude.txt
Fixes: https://github.com/nextstrain/dengue/issues/54
[MT597439](https://www.ncbi.nlm.nih.gov/nuccore/MT597439) is incorrectly annotated as `/organism="dengue virus type 2"` in NCBI but should be ``/organism="dengue virus type 4"`` based on the [submitter's publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7952331/) where they correctly assign it as DENV4/II (See Fig 1b, sample 43257 highlighted in yellow).
Separately, someone will be requesting that NCBI to correct this entry. But this commit manually corrects the serotype annotation in the annotations.tsv file in the meanwhile.
* https://github.com/nextstrain/dengue/issues/54
=> Fix serotype annotation for MT597439

ingest/defaults/annotations.tsv, ingest/defaults/config.yaml, ingest/rules/curate.smk, ingest/rules/nextclade.smk, ingest/rules/split_serotypes.smk, phylogenetic/config/color_orderings.tsv, phylogenetic/config/config_dengue.yaml, phylogenetic/rules/export.smk
For Dengue serotype, genotype, and the various methods we employ to derive them for a specific strain (NCBI, Nextclade, augur clades (Nextstrain)), this PR is an implementation of consistent metadata column names and auspice color titles following the plan in https://github.com/nextstrain/dengue/issues/41#issuecomment-2113248913
* https://github.com/nextstrain/dengue/issues/41
Link to test builds from this branch: 
| | genome | E gene |
| :--| :-- | :--|
| all   | [all/genome](https://next.nextstrain.org/staging/dengue/trials/serogeno20240518/dengue/all/genome)     | [all/E](https://next.nextstrain.org/staging/dengue/trials/serogeno20240518/dengue/all/E)     |
| denv1 | [denv1/genome](https://next.nextstrain.org/staging/dengue/trials/serogeno20240518/dengue/denv1/genome) | …
=> Consistent serotype-genotype column names and auspice color titles

phylogenetic/config/config_dengue.yaml, phylogenetic/config/include_all.txt, phylogenetic/config/include_denv1.txt, phylogenetic/config/include_denv2.txt, phylogenetic/config/include_denv3.txt, phylogenetic/config/include_denv4.txt, phylogenetic/rules/annotate_phylogeny.smk, phylogenetic/rules/prepare_sequences.smk
Following the plan laid out in https://github.com/nextstrain/dengue/issues/21#issuecomment-2128162523
This PR is making some minor updates to the `phylogenetic` workflow to prepare for the Nextclade workflow.
* https://github.com/nextstrain/dengue/issues/56
* https://github.com/nextstrain/dengue/issues/21
* https://github.com/nextstrain/dengue/pull/25
|       | genome     | E gene    |
| :-- | :-- | :-- |
| all   | [all/genome](https://next.nextstrain.org/staging/dengue/trials/prep20240524/dengue/all/genome)     | [all/E](https://next.nextstrain.org/staging/dengue/trials/prep20240524/dengue/all/E)     |
| denv1 | [denv1/genome](https://next.nextstrain.org/staging/dengue/trials/prep20240524/dengue/denv1/genome) | [denv1/E](https://next.nextstrain.org/staging/dengue/trials/prep20240524/dengu …
=> Prepare phylogenetic workflow for Nextclade workflow

.github/workflows/ingest.yaml, .github/workflows/phylogenetic.yaml
I'll be removing the corresponding repository secrets and _that_ will actually effect the switch; this commit merely cleans up the unnecessary passing of --env.
Related-to: <https://github.com/nextstrain/private/issues/110>
=> Switch AWS credentials from a long-lived IAM user to short-lived role sessions

phylogenetic/rules/annotate_phylogeny.smk
This commit reverts the change introduced in https://github.com/nextstrain/dengue/pull/57/commits/94316551c8af6270134411305098a0694eb17811 which set the REFSEQ references as the roots in the auspice trees. Turns out this is not the desired behavior for the dengue phylogenetic trees.
Instead, we want to use the sequences and metadata to infer the ancestral root of each tree. These inferred-ancestral roots can then be used in building the nextclade datasets as hard-coded reference and root of the scaffold trees.
* https://github.com/nextstrain/dengue/pull/58
|  | genome |
| :-- | :-- |
| all   | [all/genome](https://next.nextstrain.org/staging/dengue/trials/inferroot20240603/dengue/all/genome)     | 
| denv1 | [denv1/genome](https://next.nextstrain.org/staging/dengue/trials/inferroot20240603 …
=> Hotfix: Infer ancestral root in the phylogenetic workflow

ingest/defaults/annotations.tsv, phylogenetic/config/exclude.txt
Manually check and fix serotype annotations for genbank samples that were flagged during nextclade (all) serotype testing.
https://github.com/nextstrain/dengue/pull/58#issue-2326618241
Add comments to the annotations.tsv file to explain the changes.
=> Manually fix serotype mis-annotations

ingest/defaults/config.yaml
This PR enhances the gene coverage calculation by incorporating the remaining genes. This addition provides a more comprehensive view of sequencing practices, allowing us to evaluate if data providers tend to sequence specific genes-of-interest or the whole genome.
* Somewhat related to https://github.com/nextstrain/pathogen-repo-guide/issues/50
=> Adds rest of the genes for gene coverage columns

phylogenetic/config/exclude.txt
Added 40 outlier genomes found by Hill et al 2024. See [issue 83](https://github.com/nextstrain/dengue/issues/83#issuecomment-2405537358)
=> Added outlier sequences as per request raised in Issue 83

phylogenetic/defaults/config_dengue.yaml, phylogenetic/rules/prepare_sequences.smk
Increased the subsampling of the `all` trees to align more closely with the number of tips in the serotype-specific trees (approximately 4K tips). After exploring a few implementation approaches, this method was selected as the most straightforward and effective for now.
Local tests show the following subsampling results:
* genome: 3869 strains passed all filters
* E: 3931 strains passed all filters
[Edit: Added later, sorry I should have written more detail. Questions or suggestions are still welcome]
1. **sequences_per_group**: Increase the `all` `sequences_per_group` parameter to get approximately 4k samples.
1. ~~This approach is implemented in this PR.~~ --> Switched to approach 2
2. **subsample_max_sequences**: Simplify the subsampling logic by setting subsampling to …
=> Phylogenetic: Increase sampling in the `all` tree to nearly 4K tips

ingest/defaults/config.yaml, ingest/rules/nextclade.smk
Instead of overriding default alignment parameters, use the parameters specified in the Nextclade dataset. This prevents unexpected results when Nextclade dataset developers define alignment parameters and downstream users also make adjustments.
|       | genome                                                                                                         | E gene                                                                                               |
| :---- | -------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------- |
| all   | [all/genome](https://next.nextstrain.org/staging/dengue/trials/20250318/dengue/all/genome?c= …
=> Avoid overriding the default parameters in the community-contributed Nextclade datasets

CHANGELOG.md, phylogenetic/Snakefile, phylogenetic/build-configs/ci/config.yaml, phylogenetic/defaults/config_dengue.yaml, phylogenetic/rules/config.smk
Allow users to define serotypes and genes through the config. 
Includes config validation to ensure that user provided values are the expected values supported by the workflow. 
Also includes change to reduce CI runtime by only running a subset of the phylo builds.
=> phylogenetic: Allow users to define serotypes and genes
